### PR TITLE
Use suspend APIs in kotlin example

### PR DESCRIPTION
**Pull request by ccen-stripe**
use suspend APIs in kotlin example

### CODE REVIEW

**Comment by cjavilla-stripe** [comment]
Hey @ccen-stripe Any chance you would be open to making these same updates in the new accept-a-payment sample? https://github.com/stripe-samples/accept-a-payment We're working on deprecating the samples where we show individual payment methods and instead are trying to fill out the canonical accept-a-payment one.

**Comment by ccen-stripe** [comment]
will do!

**Comment by cjavilla-stripe** [comment]
Thanks, @ccen-stripe! Leaving this review for @mshafrir-stripe (wish I knew Android!)  :)

**Review by mshafrir-stripe — APPROVED** [review]

**Comment by S-makes** [comment]
Sبتاريخ ٠٦‏/٠٥‏/٢٠٢١ ٦:٠٠ م، كتب Michael Shafrir ***@***.***>:
@mshafrir-stripe approved this pull request.

**Pull request merged**
